title: Vaisakh S | Technical Blog
author: Vaisakh S
email: vaishakhsasikumar@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A Full Stack Developer with experience in the Manufacturing and Financial Sector. 
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Vaisakh S
  tagline: Full Stack Developer.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

 # generate social links in footer
  social_links:
    twitter: VSK_cool
    github:  vaisakhsasikumar
    linkedIn: in/vaisakh-s
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
